#pragma once

#define CODEX_PARTNER_VERSION_MAJOR 0
#define CODEX_PARTNER_VERSION_MINOR 0
#define CODEX_PARTNER_VERSION_PATCH 0
#define CODEX_PARTNER_VERSION_BUILD 0

#define CODEX_PARTNER_VERSION_TUPLE 0,0,0,0
#define CODEX_PARTNER_VERSION_STRING "0.0.0"
#define CODEX_PARTNER_VERSION_WIDE L"0.0.0"
